server:
  port: 8284

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:cab-database
    driverClassName: org.h2.Driver
    username: cabuser
    password: cabPassword0
  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    org.springframework: ERROR
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: cab-logs.log